### ISSUE TITLE
add_v2 not working

### ISSUE THREAD

**Issue by Silmathoron** [GLMF/GLMF179#1]
I tried to use LMF 179 as a tutorial to begin with pycuda, but though the first version of "add" worked perfectly, as soon as I tried to use the **device** function with the **shared** array in "add_v2", the result I get is wrong (my final array contains only ones whatever I do).
Is this code working properly on your computer? I can't imagine a reason why "add" works on mine and "add_V2" does not...
Best regards

**Comment by tcolombo** [comment]
The results obtained using the two scripts are the same : [2 2 2 ....... 2]. All is working !
Perhaps inspect your pycuda installation? It's weird...

**Comment by Silmathoron** [comment]
I kept looking at it yesterday and I managed to make it work by adding the following modification :
in the _ _global _ _ function, I used "int index = ...\ result[index] = add()[index]".
I'm not really sure what the difference is, but directly passing the array doesn't work, while assigning each value individually does...
