### ISSUE TITLE
add v2 ne fonctionne pas

### ISSUE THREAD

**Issue by zorg724** [GLMF/GLMF179#2]
Bonjour, le code ne peut pas fonctionner: le tableau reste à zero: 
 /test_cuda/add_v2.py 
  UserWarning: The CUDA compiler succeeded, but said the following:
kernel.cu(13): warning: parameter "result" was set but never used

  """)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

En effet,   __shared__ int result[400];  est déclaré statiquement. Le tableau result[400] n'existe plus au sortir de la fonction int *add(int *a, int *b). On ne peut pas retourner un pointeur sur un tableau s'il est défini dans la fonction...
Salutations
zorgui.

**Comment by tcolombo** [comment]
Bonjour,

shared c'est pour de la mémoire partagée... donc oui, on peut accéder aux données.
Ce code fonctionnait il y a un peu plus de 5 ans, je ne sais pas quelles ont été les modifications de l'API depuis...
Sinon l'article avec toutes les explications est toujours disponible [ici] (https://connect.ed-diamond.com/GNU-Linux-Magazine/GLMF-179/Optimisation-de-code-Python-des-fractales-au-pays-des-serpents)

Cordialement,
